//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBS_Services
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class rewardsdbEntities : DbContext
    {
        public rewardsdbEntities()
            : base("name=rewardsdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<rewardsmaster> rewardsmasters { get; set; }
        public DbSet<rewardstransaction> rewardstransactions { get; set; }
        public DbSet<userrewardsinfo> userrewardsinfoes { get; set; }
    }
}
