//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBS_Services
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class rewardsdbEntities1 : DbContext
    {
        public rewardsdbEntities1()
            : base("name=rewardsdbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<rewardsmaster> rewardsmasters { get; set; }
        public virtual DbSet<rewardstransaction> rewardstransactions { get; set; }
        public virtual DbSet<userrewardsinfo> userrewardsinfoes { get; set; }
    }
}
