//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBS_Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class rewardsmaster
    {
        public int rewardID { get; set; }
        public string rewardName { get; set; }
        public string rewardDescription { get; set; }
        public byte[] rewardPicture { get; set; }
        public Nullable<int> rewardPoints { get; set; }
    }
}
