//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBS_Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class reward
    {
        public int rewardsID { get; set; }
        public string rewardsName { get; set; }
        public string rewardsDescription { get; set; }
    }
}
